### ISSUE TITLE
Small issue with count_frames.py

### ISSUE THREAD

**Issue by RodGal-2020** [m-decoster/ChaLearn-2021-LAP#1]
Hello there,

While executing the [dataset prepations](https://github.com/m-decoster/ChaLearn-2021-LAP#dataset-preparations), more precisely, this part: "*Finally, run the `count_frames`.py script...*", count_frames returns an error:

![image](https://user-images.githubusercontent.com/96689554/181192855-28eb5d9c-c22f-469e-9e93-b6a1e575a3d4.png)

And launching the help for it, with `python count_frames.py -h`, it returns:

![image](https://user-images.githubusercontent.com/96689554/181193008-157c5b10-de5a-48fe-9f6c-77a76ca64a19.png)

So it just looks like "-i" is not considered as a parameter for the function. With "--input_dir" it works just fine.

**Comment by m-decoster** [comment]
Hi,

Thanks for reporting this issue. I've updated the README to indicate the correct syntax.

See 31eb94b9cd4988eb1d3bb4817e86c73b8d97d555.
